In [1]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import h2o
from h2o.automl import H2OAutoML

In [2]:
# JRE 설치가 필요하다
h2o.init(max_mem_size='16G')

Checking whether there is an H2O instance running at http://localhost:54321 . connected.

--------------------------  ---------------------------------------------------------
H2O cluster uptime:         1 hour 46 mins
H2O cluster timezone:       Asia/Seoul
H2O data parsing timezone:  UTC
H2O cluster version:        3.26.0.5
H2O cluster version age:    10 days
H2O cluster name:           H2O_from_python_HPE_avufhw
H2O cluster total nodes:    1
H2O cluster free memory:    15.99 Gb
H2O cluster total cores:    6
H2O cluster allowed cores:  6
H2O cluster status:         locked, healthy
H2O connection url:         http://localhost:54321
H2O connection proxy:
H2O internal security:      False
H2O API Extensions:         Amazon S3, Algos, AutoML, Core V3, TargetEncoder, Core V4
Python version:             3.7.4 final
--------------------------  ---------------------------------------------------------

In [13]:
%%time
train = h2o.import_file("../data/train2.csv")
test = h2o.import_file("../data/test2.csv")

Parse progress: |█████████████████████████████████████████████████████████| 100%
Parse progress: |█████████████████████████████████████████████████████████| 100%
Wall time: 10.3 s

In [14]:
y = 'Survived'
x = [x for x in train.columns if x not in y]
print(len(x), x)

train[y] = train[y].asfactor()

34 ['Fare', 'PassengerId', 'Pclass', 'Women', 'FamilySize', 'Mother', 'Free', 'Age_Child', 'Age_Young Adult', 'Age_Adult', 'Age_Older Adult', 'Age_Senior', 'Cabin_A', 'Cabin_B', 'Cabin_C', 'Cabin_D', 'Cabin_E', 'Cabin_F', 'Cabin_G', 'Embarked_C', 'Embarked_Q', 'Embarked_S', 'Title_Dr', 'Title_Master', 'Title_Miss', 'Title_Mr', 'Title_Mrs', 'Title_Other', 'TypeOfTicket_A5', 'TypeOfTicket_CA', 'TypeOfTicket_NO', 'TypeOfTicket_PC', 'TypeOfTicket_SOTONOQ', 'TypeOfTicket_other']

In [15]:
#aml = H2OAutoML(max_models=30, seed=45, max_runtime_secs=18000)
aml = H2OAutoML(max_models=20, seed=45, max_runtime_secs=1800)
aml.train(x=x, y=y, training_frame=train)

AutoML progress: |████████████████████████████████████████████████████████| 100%

In [16]:
lb = aml.leaderboard
lb.head(rows=lb.nrows)  # Print all rows instead of default (10 rows)

model_id,auc,logloss,mean_per_class_error,rmse,mse
GBM_grid_1_AutoML_20190926_173852_model_6,0.878634,0.497263,0.173066,0.397003,0.157611
GBM_2_AutoML_20190926_173852,0.877347,0.401337,0.167649,0.348593,0.121517
StackedEnsemble_BestOfFamily_AutoML_20190926_173852,0.875651,0.394214,0.173449,0.347508,0.120762
GBM_4_AutoML_20190926_173852,0.875313,0.410133,0.169375,0.350895,0.123128
GBM_3_AutoML_20190926_173852,0.875198,0.406615,0.158758,0.350334,0.122734
StackedEnsemble_AllModels_AutoML_20190926_173852,0.873486,0.39491,0.172802,0.347762,0.120938
DRF_1_AutoML_20190926_173852,0.871284,0.467064,0.178674,0.359632,0.129335
XRT_1_AutoML_20190926_173852,0.87003,0.437029,0.186152,0.360376,0.129871
GBM_1_AutoML_20190926_173852,0.86881,0.410425,0.176996,0.352595,0.124323
DeepLearning_grid_1_AutoML_20190926_173852_model_2,0.86804,0.487293,0.183755,0.362683,0.131539
GBM_grid_1_AutoML_20190926_173852_model_3,0.867891,0.45908,0.184163,0.366073,0.13401
GBM_grid_1_AutoML_20190926_173852_model_2,0.866621,0.495861,0.19188,0.396727,0.157393
DeepLearning_grid_1_AutoML_20190926_173852_model_1,0.865508,0.499145,0.177524,0.368179,0.135556
GLM_grid_1_AutoML_20190926_173852_model_1,0.861537,0.432098,0.180711,0.365033,0.133249
GBM_grid_1_AutoML_20190926_173852_model_5,0.860477,0.653132,0.185001,0.480046,0.230445
DeepLearning_grid_1_AutoML_20190926_173852_model_3,0.856049,0.558394,0.195811,0.380304,0.144631
GBM_grid_1_AutoML_20190926_173852_model_1,0.855348,0.595179,0.196913,0.390357,0.152379
DeepLearning_grid_1_AutoML_20190926_173852_model_5,0.854169,0.447154,0.197273,0.367791,0.135271
GBM_5_AutoML_20190926_173852,0.852265,0.443787,0.214049,0.37371,0.139659
DeepLearning_grid_1_AutoML_20190926_173852_model_4,0.850467,0.544829,0.206883,0.382954,0.146654
DeepLearning_1_AutoML_20190926_173852,0.832963,0.486143,0.208465,0.382363,0.146202
GBM_grid_1_AutoML_20190926_173852_model_4,0.827256,0.781742,0.221335,0.42443,0.180141

In [7]:
aml.leader

Model Details
=============
H2OGradientBoostingEstimator :  Gradient Boosting Machine
Model Key:  GBM_2_AutoML_20190926_173626


Model Summary:

,,number_of_trees,number_of_internal_trees,model_size_in_bytes,min_depth,max_depth,mean_depth,min_leaves,max_leaves,mean_leaves
0,,40.0,40.0,18202.0,7.0,7.0,7.0,11.0,45.0,31.45

ModelMetricsBinomial: gbm
** Reported on train data. **

MSE: 0.06937710598273879
RMSE: 0.2633953416116898
LogLoss: 0.2487783602457602
Mean Per-Class Error: 0.09605982168536098
AUC: 0.9699400291865061
pr_auc: 0.9567527396593531
Gini: 0.9398800583730123

Confusion Matrix (Act/Pred) for max f1 @ threshold = 0.49438773942719066:

              0      1   Error           Rate
0      0  527.0   22.0  0.0401   (22.0/549.0)
1      1   52.0  290.0   0.152   (52.0/342.0)
2  Total  579.0  312.0  0.0831   (74.0/891.0)

Maximum Metrics: Maximum metrics at their respective thresholds

                         metric  threshold       value    idx
0                        max f1   0.494388    0.886850  177.0
1                        max f2   0.232915    0.908319  243.0
2                  max f0point5   0.613718    0.917462  151.0
3                  max accuracy   0.500903    0.916947  173.0
4                 max precision   0.988430    1.000000    0.0
5                    max recall   0.093972    1.000000  332.0
6               max specificity   0.988430    1.000000    0.0
7              max absolute_mcc   0.500903    0.823853  173.0
8    max min_per_class_accuracy   0.312007    0.903461  216.0
9   max mean_per_class_accuracy   0.494388    0.903940  177.0
10                      max tns   0.988430  549.000000    0.0
11                      max fns   0.988430  341.000000    0.0
12                      max fps   0.026019  549.000000  399.0
13                      max tps   0.093972  342.000000  332.0
14                      max tnr   0.988430    1.000000    0.0
15                      max fnr   0.988430    0.997076    0.0
16                      max fpr   0.026019    1.000000  399.0
17                      max tpr   0.093972    1.000000  332.0

Gains/Lift Table: Avg response rate: 38.38 %, avg score: 38.47 %

,,group,cumulative_data_fraction,lower_threshold,lift,cumulative_lift,response_rate,score,cumulative_response_rate,cumulative_score,capture_rate,cumulative_capture_rate,gain,cumulative_gain
0,,1,0.010101,0.979438,2.605263,2.605263,1.000000,0.982712,1.000000,0.982712,0.026316,0.026316,160.526316,160.526316
1,,2,0.020202,0.975406,2.605263,2.605263,1.000000,0.977880,1.000000,0.980296,0.026316,0.052632,160.526316,160.526316
2,,3,0.030303,0.969024,2.605263,2.605263,1.000000,0.972983,1.000000,0.977858,0.026316,0.078947,160.526316,160.526316
3,,4,0.040404,0.964735,2.605263,2.605263,1.000000,0.967242,1.000000,0.975204,0.026316,0.105263,160.526316,160.526316
4,,5,0.050505,0.961779,2.605263,2.605263,1.000000,0.962850,1.000000,0.972733,0.026316,0.131579,160.526316,160.526316
5,,6,0.101010,0.940241,2.605263,2.605263,1.000000,0.953283,1.000000,0.963008,0.131579,0.263158,160.526316,160.526316
6,,7,0.150393,0.916420,2.605263,2.605263,1.000000,0.927993,1.000000,0.951511,0.128655,0.391813,160.526316,160.526316
7,,8,0.200898,0.873661,2.605263,2.605263,1.000000,0.896235,1.000000,0.937614,0.131579,0.523392,160.526316,160.526316
8,,9,0.300786,0.662406,2.312537,2.508052,0.887640,0.778866,0.962687,0.884896,0.230994,0.754386,131.253696,150.805185
9,,10,0.400673,0.320557,1.434358,2.240380,0.550562,0.491416,0.859944,0.786801,0.143275,0.897661,43.435837,124.038036
10,,11,0.500561,0.173211,0.585452,1.910137,0.224719,0.237641,0.733184,0.677216,0.058480,0.956140,-41.454760,91.013689
11,,12,0.600449,0.124589,0.351271,1.650812,0.134831,0.144161,0.633645,0.588539,0.035088,0.991228,-64.872856,65.081161
12,,13,0.700337,0.099303,0.058545,1.423710,0.022472,0.109585,0.546474,0.520227,0.005848,0.997076,-94.145476,42.370951
13,,14,0.800224,0.076549,0.029273,1.249649,0.011236,0.087882,0.479663,0.466260,0.002924,1.000000,-97.072738,24.964937
14,,15,0.900112,0.060041,0.000000,1.110973,0.000000,0.067741,0.426434,0.422035,0.000000,1.000000,-100.000000,11.097257
15,,16,1.000000,0.025849,0.000000,1.000000,0.000000,0.048374,0.383838,0.384711,0.000000,1.000000,-100.000000,0.000000

ModelMetricsBinomial: gbm
** Reported on cross-validation data. **

MSE: 0.12151712085357658
RMSE: 0.3485930591012629
LogLoss: 0.4013370205637921
Mean Per-Class Error: 0.16764931454318854
AUC: 0.8773474365939135
pr_auc: 0.8444114494968255
Gini: 0.7546948731878269

Confusion Matrix (Act/Pred) for max f1 @ threshold = 0.27455494730072416:

              0      1   Error            Rate
0      0  450.0   99.0  0.1803    (99.0/549.0)
1      1   53.0  289.0   0.155    (53.0/342.0)
2  Total  503.0  388.0  0.1706   (152.0/891.0)

Maximum Metrics: Maximum metrics at their respective thresholds

                         metric  threshold       value    idx
0                        max f1   0.274555    0.791781  232.0
1                        max f2   0.225047    0.827257  248.0
2                  max f0point5   0.723246    0.830684  112.0
3                  max accuracy   0.426177    0.839506  185.0
4                 max precision   0.983817    1.000000    0.0
5                    max recall   0.036965    1.000000  391.0
6               max specificity   0.983817    1.000000    0.0
7              max absolute_mcc   0.379495    0.659107  201.0
8    max min_per_class_accuracy   0.302919    0.824561  224.0
9   max mean_per_class_accuracy   0.274555    0.832351  232.0
10                      max tns   0.983817  549.000000    0.0
11                      max fns   0.983817  341.000000    0.0
12                      max fps   0.023044  549.000000  399.0
13                      max tps   0.036965  342.000000  391.0
14                      max tnr   0.983817    1.000000    0.0
15                      max fnr   0.983817    0.997076    0.0
16                      max fpr   0.023044    1.000000  399.0
17                      max tpr   0.036965    1.000000  391.0

Gains/Lift Table: Avg response rate: 38.38 %, avg score: 38.07 %

,,group,cumulative_data_fraction,lower_threshold,lift,cumulative_lift,response_rate,score,cumulative_response_rate,cumulative_score,capture_rate,cumulative_capture_rate,gain,cumulative_gain
0,,1,0.010101,0.975765,2.605263,2.605263,1.000000,0.978970,1.000000,0.978970,0.026316,0.026316,160.526316,160.526316
1,,2,0.020202,0.971911,2.605263,2.605263,1.000000,0.974058,1.000000,0.976514,0.026316,0.052632,160.526316,160.526316
2,,3,0.030303,0.964202,2.605263,2.605263,1.000000,0.968672,1.000000,0.973900,0.026316,0.078947,160.526316,160.526316
3,,4,0.040404,0.960783,2.315789,2.532895,0.888889,0.963142,0.972222,0.971211,0.023392,0.102339,131.578947,153.289474
4,,5,0.050505,0.957741,2.026316,2.431579,0.777778,0.959162,0.933333,0.968801,0.020468,0.122807,102.631579,143.157895
5,,6,0.101010,0.938370,2.373684,2.402632,0.911111,0.948169,0.922222,0.958485,0.119883,0.242690,137.368421,140.263158
6,,7,0.150393,0.902608,2.546053,2.449725,0.977273,0.923471,0.940299,0.946988,0.125731,0.368421,154.605263,144.972506
7,,8,0.200898,0.837150,2.373684,2.430609,0.911111,0.874136,0.932961,0.928673,0.119883,0.488304,137.368421,143.060864
8,,9,0.300786,0.621774,1.844175,2.235860,0.707865,0.731917,0.858209,0.863332,0.184211,0.672515,84.417504,123.586017
9,,10,0.400673,0.354040,1.287995,1.999558,0.494382,0.474634,0.767507,0.766430,0.128655,0.801170,28.799527,99.955772
10,,11,0.500561,0.192384,0.731815,1.746578,0.280899,0.255882,0.670404,0.664549,0.073099,0.874269,-26.818451,74.657777
11,,12,0.600449,0.139696,0.204908,1.490113,0.078652,0.159676,0.571963,0.580561,0.020468,0.894737,-79.509166,49.011313
12,,13,0.700337,0.105105,0.204908,1.306807,0.078652,0.122254,0.501603,0.515194,0.020468,0.915205,-79.509166,30.680668
13,,14,0.800224,0.075180,0.292726,1.180224,0.112360,0.088965,0.453015,0.461990,0.029240,0.944444,-70.727380,18.022440
14,,15,0.900112,0.056466,0.263454,1.078488,0.101124,0.065054,0.413965,0.417941,0.026316,0.970760,-73.654642,7.848799
15,,16,1.000000,0.023044,0.292726,1.000000,0.112360,0.044683,0.383838,0.380657,0.029240,1.000000,-70.727380,0.000000

Cross-Validation Metrics Summary:

,,mean,sd,cv_1_valid,cv_2_valid,cv_3_valid,cv_4_valid,cv_5_valid
0,accuracy,0.8462118,0.030557865,0.87150836,0.85393256,0.7977528,0.8707865,0.83707863
1,auc,0.87865365,0.03509383,0.9213699,0.8909328,0.8306818,0.892818,0.85746574
2,err,0.15378821,0.030557865,0.12849163,0.14606741,0.20224719,0.12921348,0.16292135
3,err_count,27.4,5.4129477,23.0,26.0,36.0,23.0,29.0
4,f0point5,0.7926044,0.046004508,0.8384146,0.8136483,0.7178218,0.8088235,0.78431374
5,f1,0.80765724,0.028604174,0.8270677,0.82666665,0.7631579,0.8270677,0.79432625
6,f2,0.8242981,0.017875489,0.81602377,0.8401084,0.8146067,0.84615386,0.8045977
7,lift_top_group,2.6098633,0.12274331,2.6323528,2.4383562,2.6176472,2.78125,2.5797102
8,logloss,0.4014033,0.0613556,0.34233013,0.37180746,0.49443465,0.36737773,0.4310666
9,max_per_class_error,0.18145117,0.03798574,0.19117647,0.15068494,0.23636363,0.140625,0.1884058
10,mcc,0.6824566,0.05323789,0.7253952,0.7013525,0.6001156,0.72546667,0.65995306
11,mean_per_class_accuracy,0.8443142,0.02408485,0.8593667,0.853229,0.80828875,0.868284,0.8324026
12,mean_per_class_error,0.1556858,0.02408485,0.14063329,0.14677104,0.19171123,0.13171601,0.1675974
13,mse,0.12153586,0.019917803,0.104842335,0.1106095,0.15249403,0.109263964,0.13046946
14,precision,0.7833408,0.0575917,0.84615386,0.8051948,0.6904762,0.79710144,0.7777778
15,r2,0.4855331,0.08398724,0.5549479,0.54278517,0.35406142,0.52550447,0.4503664
16,recall,0.8364098,0.024207689,0.8088235,0.84931505,0.85294116,0.859375,0.8115942
17,rmse,0.34772703,0.027878592,0.32379365,0.33258006,0.39050484,0.330551,0.36120555
18,specificity,0.8522186,0.05436923,0.9099099,0.85714287,0.76363635,0.877193,0.853211

Scoring History:

,,timestamp,duration,number_of_trees,training_rmse,training_logloss,training_auc,training_pr_auc,training_lift,training_classification_error
0,,2019-09-26 17:36:30,0.265 sec,0.0,0.486319,0.665912,0.500000,0.000000,1.000000,0.616162
1,,2019-09-26 17:36:30,0.265 sec,5.0,0.390259,0.486854,0.924001,0.900669,2.605263,0.132435
2,,2019-09-26 17:36:30,0.281 sec,10.0,0.341340,0.399481,0.940253,0.920676,2.605263,0.120090
3,,2019-09-26 17:36:30,0.297 sec,15.0,0.314700,0.348014,0.946836,0.922571,2.605263,0.109989
4,,2019-09-26 17:36:30,0.297 sec,20.0,0.299830,0.316975,0.952327,0.934574,2.605263,0.106622
5,,2019-09-26 17:36:30,0.312 sec,25.0,0.287568,0.292648,0.957395,0.934895,2.605263,0.098765
6,,2019-09-26 17:36:30,0.328 sec,30.0,0.279834,0.277297,0.961253,0.939786,2.605263,0.092031
7,,2019-09-26 17:36:30,0.328 sec,35.0,0.269855,0.260800,0.966859,0.953056,2.605263,0.085297
8,,2019-09-26 17:36:30,0.343 sec,40.0,0.263395,0.248778,0.969940,0.956753,2.605263,0.083053

Variable Importances:

              variable  relative_importance  scaled_importance  percentage
0             Title_Mr           202.924362           1.000000    0.269045
1                Women           122.397087           0.603166    0.162279
2          PassengerId            98.360840           0.484717    0.130410
3                 Fare            85.049461           0.419119    0.112762
4           FamilySize            55.729565           0.274632    0.073888
5              Cabin_G            41.270485           0.203379    0.054718
6               Pclass            29.026882           0.143043    0.038485
7            Age_Adult            14.031649           0.069147    0.018604
8            Age_Child            11.502393           0.056683    0.015250
9         Title_Master            11.476274           0.056554    0.015216
10         Title_Other            11.291540           0.055644    0.014971
11          Embarked_S             9.383588           0.046242    0.012441
12     TypeOfTicket_NO             8.771204           0.043224    0.011629
13           Title_Mrs             8.131823           0.040073    0.010781
14             Cabin_E             7.878960           0.038827    0.010446
15             Cabin_C             7.335801           0.036150    0.009726
16          Title_Miss             6.879523           0.033902    0.009121
17     Age_Young Adult             5.277559           0.026008    0.006997
18          Embarked_Q             4.107899           0.020243    0.005446
19  TypeOfTicket_other             3.174492           0.015644    0.004209

See the whole table with table.as_data_frame()

In [8]:
h2o.remove(train)
test = h2o.import_file("../data/test2.csv")

Parse progress: |█████████████████████████████████████████████████████████| 100%

In [9]:
preds = aml.predict(test)
preds['p1'].as_data_frame().values.flatten().shape

gbm prediction progress: |████████████████████████████████████████████████| 100%

(418,)

In [10]:
print(preds)
preds.to_csv('./output/predic.csv')

predict,p0,p1
0,0.947802,0.0521985
1,0.243472,0.756528
0,0.950678,0.049322
0,0.941091,0.0589091
1,0.399035,0.600965
0,0.955386,0.0446144
1,0.441074,0.558926
0,0.858636,0.141364
1,0.0697282,0.930272
0,0.967138,0.0328617

AttributeError: 'H2OFrame' object has no attribute 'to_csv'

In [ ]:
col0 = test["PassengerId"].as_data_frame().values.flatten()
col1 = preds['predict'].as_data_frame().values.flatten()

my = list(zip(col0, col1))
submit = pd.DataFrame(my, columns = ["PassengerId", "Survived"])

print(submit['Survived'].value_counts())
submit.to_csv("submissionH2O.csv", index = False)

In [ ]:
len(myDic)

In [ ]:
!kaggle competitions submit -c titanic -f submission2.csv -m "Message"